classdef Param_CORNER
    properties
        
        visualization = 'summary';
        generate_data = false;
        
        map_type = 'corner';
        map_generate = true;
        mapping = 'increment';
        
        % Gloabal Map parameters
        globalmap = struct('width', 20, ...
                            'height', 20, ...
                            'inflation', 0.4, ...
                            'resolution', 5, ...
                            'numsamples', 80 ...
                            );
        % Local Map parameters
        localmap = struct('width', 20, ...
                          'height', 20, ...
                          'resolution', 5);
                      
        hilbertmap = struct('enable', true, ...
                          'kernel', 'rbf', ...
                          'momentum', 0, ...%Momentum method flag for SGD
                          'num_samples', 100, ...
                          'resolution', 2, ...
                          'radius', 1.5, ...
                          'pattern', 'grid', ...
                          'max_iteration', 20, ...
                          'learningrate', 0.3, ...
                          'render', true, ...
                          'render_resolution', 1, ...
                          'plot', true);

        sensor = struct('fov', 0.5*pi(), ...
                        'maxrange', 20);
        
        mav = struct('size', 0.5);
        
        % Planner
        planner = struct('type', 'hilbertchomp', ...
                         'num_segments', 1, ...
                         'cost_der', 0.01, ...
                         'cost_coll', 20, ...
                         'cost_goal', 10, ...
                         'cost_entropy', 0.1);
        plan_horizon = 5;
        update_rate = 1;        
        
        global_planner = struct('type', 'polynomial', ...
                                'map', 'disable');
        globalreplan = true;
        localgoal = 'nextbestview'
        
        start_point = [5.0 5.0];
        goal_point = [15.0 15.0];

        
    end 
    methods
    end
end