classdef Param_RANDOMFOREST
    properties
        
        visualization = 'summary';
        generate_data = true;
        
        map_type = 'randomforest';
        map_generate = true;
        mapping = 'increment';
        
        % Gloabal Map parameters
        globalmap = struct('width', 20, ...
                            'height', 20, ...
                            'inflation', 0.4, ...
                            'resolution', 10, ...
                            'numsamples', 80 ...
                            );
        % Local Map parameters
        localmap = struct('width', 10, ...
                          'height', 10, ...
                          'resolution', 10);
                      
        hilbertmap = struct('enable', true, ...
                            'kernel', 'rbf', ...
                            'momentum', 0, ...%Momentum method flag for SGD
                            'num_samples', 100, ...
                            'resolution', 4, ...
                            'radius', 1.5, ...
                            'max_iteration', 20, ...
                            'learningrate', 0.3, ...
                            'render', true, ...
                            'render_resolution', 1, ...
                            'plot', true);

        sensor = struct('fov', 0.5*pi(), ...
                        'maxrange', 5);
        
        mav = struct('size', 0.5);
        
        % Planner
        planner = struct('type', 'informativechomp', ...
                         'num_segments', 1);
        plan_horizon = 5;
        update_rate = 1;        
        
        global_planner = 'optimistic';
        globalreplan = true;
        localgoal = 'random'
        
        start_point = [2.0 2.0];
        goal_point = [18.0 18.0];

        
    end 
    methods
    end
end